# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1200, 700)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.lineEditSend = QtWidgets.QComboBox(self.centralwidget)
        self.lineEditSend.setMinimumSize(QtCore.QSize(500, 0))
        self.lineEditSend.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.lineEditSend.setEditable(True)
        self.lineEditSend.setObjectName("lineEditSend")
        self.lineEditSend.setStyleSheet("background-color: balck;\n"
                                           "color: white;")
        self.gridLayout.addWidget(self.lineEditSend, 2, 0, 1, 1)
        self.buttonSend = QtWidgets.QPushButton(self.centralwidget)
        self.buttonSend.setMinimumSize(QtCore.QSize(100, 0))
        self.buttonSend.setMaximumSize(QtCore.QSize(100, 16777215))
        self.buttonSend.setObjectName("buttonSend")
        self.gridLayout.addWidget(self.buttonSend, 2, 1, 1, 1)
        self.textEditRecvive = QtWidgets.QTextBrowser(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textEditRecvive.sizePolicy().hasHeightForWidth())
        self.textEditRecvive.setSizePolicy(sizePolicy)
        self.textEditRecvive.setMinimumSize(QtCore.QSize(600, 596))
        self.textEditRecvive.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.textEditRecvive.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.textEditRecvive.setStyleSheet("background-color: balck;\n"
"color: white;")
        self.textEditRecvive.setObjectName("textEditRecvive")
        self.gridLayout.addWidget(self.textEditRecvive, 1, 0, 1, 2)
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setMinimumSize(QtCore.QSize(570, 0))
        self.tabWidget.setMaximumSize(QtCore.QSize(570, 16777215))
        self.tabWidget.setObjectName("tabWidget")
        self.tab_serial = QtWidgets.QWidget()
        self.tab_serial.setObjectName("tab_serial")
        self.lineEditsend1 = QtWidgets.QLineEdit(self.tab_serial)
        self.lineEditsend1.setGeometry(QtCore.QRect(10, 10, 431, 21))
        self.lineEditsend1.setObjectName("lineEditsend1")
        self.checkBox1 = QtWidgets.QCheckBox(self.tab_serial)
        self.checkBox1.setGeometry(QtCore.QRect(540, 10, 21, 21))
        self.checkBox1.setText("")
        self.checkBox1.setObjectName("checkBox1")
        self.lineEdittime1 = QtWidgets.QLineEdit(self.tab_serial)
        self.lineEdittime1.setGeometry(QtCore.QRect(450, 10, 81, 21))
        self.lineEdittime1.setObjectName("lineEdittime1")
        self.lineEdittime2 = QtWidgets.QLineEdit(self.tab_serial)
        self.lineEdittime2.setGeometry(QtCore.QRect(450, 40, 81, 21))
        self.lineEdittime2.setObjectName("lineEdittime2")
        self.checkBox_2 = QtWidgets.QCheckBox(self.tab_serial)
        self.checkBox_2.setGeometry(QtCore.QRect(540, 40, 21, 21))
        self.checkBox_2.setText("")
        self.checkBox_2.setObjectName("checkBox_2")
        self.lineEdit_send2 = QtWidgets.QLineEdit(self.tab_serial)
        self.lineEdit_send2.setGeometry(QtCore.QRect(10, 40, 431, 21))
        self.lineEdit_send2.setObjectName("lineEdit_send2")
        self.lineEdittime3 = QtWidgets.QLineEdit(self.tab_serial)
        self.lineEdittime3.setGeometry(QtCore.QRect(450, 70, 81, 21))
        self.lineEdittime3.setObjectName("lineEdittime3")
        self.checkBox_3 = QtWidgets.QCheckBox(self.tab_serial)
        self.checkBox_3.setGeometry(QtCore.QRect(540, 70, 21, 21))
        self.checkBox_3.setText("")
        self.checkBox_3.setObjectName("checkBox_3")
        self.lineEditsend3 = QtWidgets.QLineEdit(self.tab_serial)
        self.lineEditsend3.setGeometry(QtCore.QRect(10, 70, 431, 21))
        self.lineEditsend3.setObjectName("lineEditsend3")
        self.lineEdittime4 = QtWidgets.QLineEdit(self.tab_serial)
        self.lineEdittime4.setGeometry(QtCore.QRect(450, 100, 81, 21))
        self.lineEdittime4.setObjectName("lineEdittime4")
        self.checkBox_4 = QtWidgets.QCheckBox(self.tab_serial)
        self.checkBox_4.setGeometry(QtCore.QRect(540, 100, 21, 21))
        self.checkBox_4.setText("")
        self.checkBox_4.setObjectName("checkBox_4")
        self.lineEditsend4 = QtWidgets.QLineEdit(self.tab_serial)
        self.lineEditsend4.setGeometry(QtCore.QRect(10, 100, 431, 21))
        self.lineEditsend4.setObjectName("lineEditsend4")
        self.lineEdittime5 = QtWidgets.QLineEdit(self.tab_serial)
        self.lineEdittime5.setGeometry(QtCore.QRect(450, 130, 81, 21))
        self.lineEdittime5.setObjectName("lineEdittime5")
        self.checkBox_5 = QtWidgets.QCheckBox(self.tab_serial)
        self.checkBox_5.setGeometry(QtCore.QRect(540, 130, 21, 21))
        self.checkBox_5.setText("")
        self.checkBox_5.setObjectName("checkBox_5")
        self.lineEditsend5 = QtWidgets.QLineEdit(self.tab_serial)
        self.lineEditsend5.setGeometry(QtCore.QRect(10, 130, 431, 21))
        self.lineEditsend5.setObjectName("lineEditsend5")
        self.lineEdittime6 = QtWidgets.QLineEdit(self.tab_serial)
        self.lineEdittime6.setGeometry(QtCore.QRect(450, 160, 81, 21))
        self.lineEdittime6.setObjectName("lineEdittime6")
        self.checkBox_6 = QtWidgets.QCheckBox(self.tab_serial)
        self.checkBox_6.setGeometry(QtCore.QRect(540, 160, 21, 21))
        self.checkBox_6.setText("")
        self.checkBox_6.setObjectName("checkBox_6")
        self.lineEditsend6 = QtWidgets.QLineEdit(self.tab_serial)
        self.lineEditsend6.setGeometry(QtCore.QRect(10, 160, 431, 21))
        self.lineEditsend6.setObjectName("lineEditsend6")
        self.lineEdittime7 = QtWidgets.QLineEdit(self.tab_serial)
        self.lineEdittime7.setGeometry(QtCore.QRect(450, 190, 81, 21))
        self.lineEdittime7.setObjectName("lineEdittime7")
        self.checkBox_7 = QtWidgets.QCheckBox(self.tab_serial)
        self.checkBox_7.setGeometry(QtCore.QRect(540, 190, 21, 21))
        self.checkBox_7.setText("")
        self.checkBox_7.setObjectName("checkBox_7")
        self.lineEditsend7 = QtWidgets.QLineEdit(self.tab_serial)
        self.lineEditsend7.setGeometry(QtCore.QRect(10, 190, 431, 21))
        self.lineEditsend7.setObjectName("lineEditsend7")
        self.lineEdittime8 = QtWidgets.QLineEdit(self.tab_serial)
        self.lineEdittime8.setGeometry(QtCore.QRect(450, 220, 81, 21))
        self.lineEdittime8.setObjectName("lineEdittime8")
        self.checkBox_8 = QtWidgets.QCheckBox(self.tab_serial)
        self.checkBox_8.setGeometry(QtCore.QRect(540, 220, 21, 21))
        self.checkBox_8.setText("")
        self.checkBox_8.setObjectName("checkBox_8")
        self.lineEditsend8 = QtWidgets.QLineEdit(self.tab_serial)
        self.lineEditsend8.setGeometry(QtCore.QRect(10, 220, 431, 21))
        self.lineEditsend8.setObjectName("lineEditsend8")
        self.lineEdittime9 = QtWidgets.QLineEdit(self.tab_serial)
        self.lineEdittime9.setGeometry(QtCore.QRect(450, 250, 81, 21))
        self.lineEdittime9.setObjectName("lineEdittime9")
        self.checkBox_9 = QtWidgets.QCheckBox(self.tab_serial)
        self.checkBox_9.setGeometry(QtCore.QRect(540, 250, 21, 21))
        self.checkBox_9.setText("")
        self.checkBox_9.setObjectName("checkBox_9")
        self.lineEditsend9 = QtWidgets.QLineEdit(self.tab_serial)
        self.lineEditsend9.setGeometry(QtCore.QRect(10, 250, 431, 21))
        self.lineEditsend9.setObjectName("lineEditsend9")
        self.lineEdittime10 = QtWidgets.QLineEdit(self.tab_serial)
        self.lineEdittime10.setGeometry(QtCore.QRect(450, 280, 81, 21))
        self.lineEdittime10.setObjectName("lineEdittime10")
        self.checkBox_10 = QtWidgets.QCheckBox(self.tab_serial)
        self.checkBox_10.setGeometry(QtCore.QRect(540, 280, 21, 21))
        self.checkBox_10.setText("")
        self.checkBox_10.setObjectName("checkBox_10")
        self.lineEditsend10 = QtWidgets.QLineEdit(self.tab_serial)
        self.lineEditsend10.setGeometry(QtCore.QRect(10, 280, 431, 21))
        self.lineEditsend10.setObjectName("lineEditsend10")
        self.buttonSend_2 = QtWidgets.QPushButton(self.tab_serial)
        self.buttonSend_2.setGeometry(QtCore.QRect(450, 310, 101, 23))
        self.buttonSend_2.setMinimumSize(QtCore.QSize(100, 0))
        self.buttonSend_2.setMaximumSize(QtCore.QSize(150, 16777215))
        self.buttonSend_2.setObjectName("buttonSend_2")
        self.groupBox_3 = QtWidgets.QGroupBox(self.tab_serial)
        self.groupBox_3.setGeometry(QtCore.QRect(0, 340, 561, 221))
        self.groupBox_3.setObjectName("groupBox_3")
        self.tabWidget.addTab(self.tab_serial, "")
        self.tab_parse = QtWidgets.QWidget()
        self.tab_parse.setObjectName("tab_parse")
        self.groupBox = QtWidgets.QGroupBox(self.tab_parse)
        self.groupBox.setGeometry(QtCore.QRect(0, 10, 561, 241))
        self.groupBox.setObjectName("groupBox")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(10, 20, 61, 21))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(10, 50, 54, 21))
        self.label_2.setObjectName("label_2")
        self.lineEditinputIPC = QtWidgets.QLineEdit(self.groupBox)
        self.lineEditinputIPC.setGeometry(QtCore.QRect(80, 20, 471, 21))
        self.lineEditinputIPC.setObjectName("lineEditinputIPC")
        self.textEditoutputIPC = QtWidgets.QTextEdit(self.groupBox)
        self.textEditoutputIPC.setGeometry(QtCore.QRect(80, 50, 471, 111))
        self.textEditoutputIPC.setObjectName("textEditoutputIPC")
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setGeometry(QtCore.QRect(10, 170, 71, 21))
        self.label_5.setObjectName("label_5")
        self.lineEditinputIPC_file = QtWidgets.QLineEdit(self.groupBox)
        self.lineEditinputIPC_file.setGeometry(QtCore.QRect(80, 170, 471, 21))
        self.lineEditinputIPC_file.setObjectName("lineEditinputIPC_file")
        self.label_15 = QtWidgets.QLabel(self.groupBox)
        self.label_15.setGeometry(QtCore.QRect(10, 200, 71, 21))
        self.label_15.setObjectName("label_15")
        self.lineEditinputIPC_doc = QtWidgets.QLineEdit(self.groupBox)
        self.lineEditinputIPC_doc.setGeometry(QtCore.QRect(80, 200, 361, 21))
        self.lineEditinputIPC_doc.setObjectName("lineEditinputIPC_doc")
        self.button_ipcparse = QtWidgets.QPushButton(self.groupBox)
        self.button_ipcparse.setGeometry(QtCore.QRect(450, 200, 100, 23))
        self.button_ipcparse.setMinimumSize(QtCore.QSize(100, 0))
        self.button_ipcparse.setMaximumSize(QtCore.QSize(100, 16777215))
        self.button_ipcparse.setObjectName("button_ipcparse")
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab_parse)
        self.groupBox_2.setGeometry(QtCore.QRect(0, 260, 561, 311))
        self.groupBox_2.setObjectName("groupBox_2")
        self.label_3 = QtWidgets.QLabel(self.groupBox_2)
        self.label_3.setGeometry(QtCore.QRect(10, 20, 71, 21))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.groupBox_2)
        self.label_4.setGeometry(QtCore.QRect(10, 150, 71, 21))
        self.label_4.setObjectName("label_4")
        self.textEdit_beforetrans = QtWidgets.QTextEdit(self.groupBox_2)
        self.textEdit_beforetrans.setGeometry(QtCore.QRect(80, 20, 471, 121))
        self.textEdit_beforetrans.setObjectName("textEdit_beforetrans")
        self.textEdit_aftertrans = QtWidgets.QTextEdit(self.groupBox_2)
        self.textEdit_aftertrans.setGeometry(QtCore.QRect(80, 150, 471, 121))
        self.textEdit_aftertrans.setObjectName("textEdit_aftertrans")
        self.button_transspace = QtWidgets.QPushButton(self.groupBox_2)
        self.button_transspace.setGeometry(QtCore.QRect(10, 280, 100, 23))
        self.button_transspace.setMinimumSize(QtCore.QSize(100, 0))
        self.button_transspace.setMaximumSize(QtCore.QSize(100, 16777215))
        self.button_transspace.setObjectName("button_transspace")
        self.button_transtight = QtWidgets.QPushButton(self.groupBox_2)
        self.button_transtight.setGeometry(QtCore.QRect(120, 280, 100, 23))
        self.button_transtight.setMinimumSize(QtCore.QSize(100, 0))
        self.button_transtight.setMaximumSize(QtCore.QSize(100, 16777215))
        self.button_transtight.setObjectName("button_transtight")
        self.button_transbuf = QtWidgets.QPushButton(self.groupBox_2)
        self.button_transbuf.setGeometry(QtCore.QRect(230, 280, 100, 23))
        self.button_transbuf.setMinimumSize(QtCore.QSize(100, 0))
        self.button_transbuf.setMaximumSize(QtCore.QSize(100, 16777215))
        self.button_transbuf.setObjectName("button_transbuf")
        self.button_transHEX = QtWidgets.QPushButton(self.groupBox_2)
        self.button_transHEX.setGeometry(QtCore.QRect(340, 280, 100, 23))
        self.button_transHEX.setMinimumSize(QtCore.QSize(100, 0))
        self.button_transHEX.setMaximumSize(QtCore.QSize(100, 16777215))
        self.button_transHEX.setObjectName("button_transHEX")
        self.button_transchar = QtWidgets.QPushButton(self.groupBox_2)
        self.button_transchar.setGeometry(QtCore.QRect(450, 280, 100, 23))
        self.button_transchar.setMinimumSize(QtCore.QSize(100, 0))
        self.button_transchar.setMaximumSize(QtCore.QSize(100, 16777215))
        self.button_transchar.setObjectName("button_transchar")
        self.tabWidget.addTab(self.tab_parse, "")
        self.tab_plot = QtWidgets.QWidget()
        self.tab_plot.setObjectName("tab_plot")
        self.scrollArea = QtWidgets.QScrollArea(self.tab_plot)
        self.scrollArea.setGeometry(QtCore.QRect(0, 0, 561, 371))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 559, 369))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.tabWidget.addTab(self.tab_plot, "")
        self.tab_other = QtWidgets.QWidget()
        self.tab_other.setObjectName("tab_other")
        self.groupBox_4 = QtWidgets.QGroupBox(self.tab_other)
        self.groupBox_4.setGeometry(QtCore.QRect(0, 10, 561, 271))
        self.groupBox_4.setObjectName("groupBox_4")
        self.lineEdit_sourse = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEdit_sourse.setGeometry(QtCore.QRect(80, 30, 471, 21))
        self.lineEdit_sourse.setObjectName("lineEdit_sourse")
        self.label_ = QtWidgets.QLabel(self.groupBox_4)
        self.label_.setGeometry(QtCore.QRect(10, 30, 71, 21))
        self.label_.setObjectName("label_")
        self.lineEdit_obj = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEdit_obj.setGeometry(QtCore.QRect(80, 150, 471, 21))
        self.lineEdit_obj.setObjectName("lineEdit_obj")
        self.label_6 = QtWidgets.QLabel(self.groupBox_4)
        self.label_6.setGeometry(QtCore.QRect(10, 150, 71, 21))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.groupBox_4)
        self.label_7.setGeometry(QtCore.QRect(80, 60, 91, 21))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.groupBox_4)
        self.label_8.setGeometry(QtCore.QRect(340, 60, 91, 21))
        self.label_8.setObjectName("label_8")
        self.lineEdit_start1 = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEdit_start1.setGeometry(QtCore.QRect(190, 60, 101, 21))
        self.lineEdit_start1.setObjectName("lineEdit_start1")
        self.lineEdit_end1 = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEdit_end1.setGeometry(QtCore.QRect(450, 60, 101, 21))
        self.lineEdit_end1.setObjectName("lineEdit_end1")
        self.label_9 = QtWidgets.QLabel(self.groupBox_4)
        self.label_9.setGeometry(QtCore.QRect(80, 180, 91, 21))
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.groupBox_4)
        self.label_10.setGeometry(QtCore.QRect(340, 180, 91, 21))
        self.label_10.setObjectName("label_10")
        self.lineEdit_end3 = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEdit_end3.setGeometry(QtCore.QRect(450, 180, 101, 21))
        self.lineEdit_end3.setObjectName("lineEdit_end3")
        self.lineEdit_start3 = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEdit_start3.setGeometry(QtCore.QRect(190, 180, 101, 21))
        self.lineEdit_start3.setObjectName("lineEdit_start3")
        self.label_11 = QtWidgets.QLabel(self.groupBox_4)
        self.label_11.setGeometry(QtCore.QRect(80, 210, 91, 21))
        self.label_11.setObjectName("label_11")
        self.lineEdit_pad = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEdit_pad.setGeometry(QtCore.QRect(190, 210, 101, 21))
        self.lineEdit_pad.setObjectName("lineEdit_pad")
        self.label_12 = QtWidgets.QLabel(self.groupBox_4)
        self.label_12.setGeometry(QtCore.QRect(80, 120, 91, 21))
        self.label_12.setObjectName("label_12")
        self.lineEdit_source2 = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEdit_source2.setGeometry(QtCore.QRect(80, 90, 471, 21))
        self.lineEdit_source2.setText("")
        self.lineEdit_source2.setObjectName("lineEdit_source2")
        self.label_13 = QtWidgets.QLabel(self.groupBox_4)
        self.label_13.setGeometry(QtCore.QRect(340, 120, 91, 21))
        self.label_13.setObjectName("label_13")
        self.lineEdit_end2 = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEdit_end2.setGeometry(QtCore.QRect(450, 120, 101, 21))
        self.lineEdit_end2.setText("")
        self.lineEdit_end2.setObjectName("lineEdit_end2")
        self.label_14 = QtWidgets.QLabel(self.groupBox_4)
        self.label_14.setGeometry(QtCore.QRect(10, 90, 71, 21))
        self.label_14.setObjectName("label_14")
        self.lineEdit_start2 = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEdit_start2.setGeometry(QtCore.QRect(190, 120, 101, 21))
        self.lineEdit_start2.setText("")
        self.lineEdit_start2.setObjectName("lineEdit_start2")
        self.buttonstartTrans = QtWidgets.QPushButton(self.groupBox_4)
        self.buttonstartTrans.setGeometry(QtCore.QRect(450, 240, 100, 23))
        self.buttonstartTrans.setMinimumSize(QtCore.QSize(100, 0))
        self.buttonstartTrans.setMaximumSize(QtCore.QSize(100, 16777215))
        self.buttonstartTrans.setObjectName("buttonstartTrans")
        self.comboBoxfiletrans = QtWidgets.QComboBox(self.groupBox_4)
        self.comboBoxfiletrans.setGeometry(QtCore.QRect(80, 240, 211, 22))
        self.comboBoxfiletrans.setObjectName("comboBoxfiletrans")
        self.comboBoxfiletrans.addItem("")
        self.comboBoxfiletrans.addItem("")
        self.comboBoxfiletrans.addItem("")
        self.comboBoxfiletrans.addItem("")
        self.label_16 = QtWidgets.QLabel(self.groupBox_4)
        self.label_16.setGeometry(QtCore.QRect(10, 240, 71, 21))
        self.label_16.setObjectName("label_16")
        self.tabWidget.addTab(self.tab_other, "")
        self.gridLayout.addWidget(self.tabWidget, 1, 2, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1200, 23))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuLog = QtWidgets.QMenu(self.menuFile)
        self.menuLog.setObjectName("menuLog")
        self.menuEdit = QtWidgets.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        self.menuView = QtWidgets.QMenu(self.menubar)
        self.menuView.setObjectName("menuView")
        self.menuTools = QtWidgets.QMenu(self.menubar)
        self.menuTools.setObjectName("menuTools")
        self.menuOption = QtWidgets.QMenu(self.menubar)
        self.menuOption.setObjectName("menuOption")
        self.menuShow = QtWidgets.QMenu(self.menuOption)
        self.menuShow.setObjectName("menuShow")
        self.menuWindow = QtWidgets.QMenu(self.menubar)
        self.menuWindow.setObjectName("menuWindow")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setToolButtonStyle(QtCore.Qt.ToolButtonTextOnly)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionDisconnect = QtWidgets.QAction(MainWindow)
        self.actionDisconnect.setObjectName("actionDisconnect")
        self.actionRe_Connect = QtWidgets.QAction(MainWindow)
        self.actionRe_Connect.setObjectName("actionRe_Connect")
        self.actionImport = QtWidgets.QAction(MainWindow)
        self.actionImport.setObjectName("actionImport")
        self.actionExport = QtWidgets.QAction(MainWindow)
        self.actionExport.setObjectName("actionExport")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionOtherSave = QtWidgets.QAction(MainWindow)
        self.actionOtherSave.setObjectName("actionOtherSave")
        self.actionStart = QtWidgets.QAction(MainWindow)
        self.actionStart.setObjectName("actionStart")
        self.actionStop = QtWidgets.QAction(MainWindow)
        self.actionStop.setObjectName("actionStop")
        self.actionPause = QtWidgets.QAction(MainWindow)
        self.actionPause.setObjectName("actionPause")
        self.actionContinue = QtWidgets.QAction(MainWindow)
        self.actionContinue.setObjectName("actionContinue")
        self.actionOpenFile = QtWidgets.QAction(MainWindow)
        self.actionOpenFile.setObjectName("actionOpenFile")
        self.actionOpenLog = QtWidgets.QAction(MainWindow)
        self.actionOpenLog.setObjectName("actionOpenLog")
        self.actionCopy = QtWidgets.QAction(MainWindow)
        self.actionCopy.setObjectName("actionCopy")
        self.actionPaste = QtWidgets.QAction(MainWindow)
        self.actionPaste.setObjectName("actionPaste")
        self.actionCut = QtWidgets.QAction(MainWindow)
        self.actionCut.setObjectName("actionCut")
        self.actionClear = QtWidgets.QAction(MainWindow)
        self.actionClear.setObjectName("actionClear")
        self.actionClearCache = QtWidgets.QAction(MainWindow)
        self.actionClearCache.setObjectName("actionClearCache")
        self.actionClear_All = QtWidgets.QAction(MainWindow)
        self.actionClear_All.setObjectName("actionClear_All")
        self.actionFind = QtWidgets.QAction(MainWindow)
        self.actionFind.setObjectName("actionFind")
        self.actionFind_All = QtWidgets.QAction(MainWindow)
        self.actionFind_All.setObjectName("actionFind_All")
        self.actionOptions = QtWidgets.QAction(MainWindow)
        self.actionOptions.setObjectName("actionOptions")
        self.actionFast_cmd = QtWidgets.QAction(MainWindow)
        self.actionFast_cmd.setObjectName("actionFast_cmd")
        self.actionTime = QtWidgets.QAction(MainWindow)
        self.actionTime.setCheckable(True)
        self.actionTime.setObjectName("actionTime")
        self.actionNew = QtWidgets.QAction(MainWindow)
        self.actionNew.setObjectName("actionNew")
        self.actionASCII = QtWidgets.QAction(MainWindow)
        self.actionASCII.setCheckable(True)
        self.actionASCII.setObjectName("actionASCII")
        self.actionHEX = QtWidgets.QAction(MainWindow)
        self.actionHEX.setCheckable(True)
        self.actionHEX.setObjectName("actionHEX")
        self.actionSendASCII = QtWidgets.QAction(MainWindow)
        self.actionSendASCII.setCheckable(True)
        self.actionSendASCII.setObjectName("actionSendASCII")
        self.actionSendHEX = QtWidgets.QAction(MainWindow)
        self.actionSendHEX.setCheckable(True)
        self.actionSendHEX.setObjectName("actionSendHEX")
        self.actionhideright = QtWidgets.QAction(MainWindow)
        self.actionhideright.setCheckable(True)
        self.actionhideright.setObjectName("actionhideright")
        self.actionhideSend = QtWidgets.QAction(MainWindow)
        self.actionhideSend.setCheckable(True)
        self.actionhideSend.setObjectName("actionhideSend")
        self.menuLog.addAction(self.actionStart)
        self.menuLog.addAction(self.actionStop)
        self.menuLog.addAction(self.actionPause)
        self.menuLog.addAction(self.actionContinue)
        self.menuLog.addSeparator()
        self.menuLog.addAction(self.actionOpenFile)
        self.menuLog.addAction(self.actionOpenLog)
        self.menuFile.addAction(self.actionNew)
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionDisconnect)
        self.menuFile.addAction(self.actionRe_Connect)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.menuLog.menuAction())
        self.menuFile.addAction(self.actionImport)
        self.menuFile.addAction(self.actionExport)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionOtherSave)
        self.menuEdit.addAction(self.actionCopy)
        self.menuEdit.addAction(self.actionPaste)
        self.menuEdit.addAction(self.actionCut)
        self.menuEdit.addSeparator()
        self.menuEdit.addAction(self.actionClear)
        self.menuEdit.addAction(self.actionClearCache)
        self.menuEdit.addAction(self.actionClear_All)
        self.menuView.addAction(self.actionFind)
        self.menuView.addAction(self.actionFind_All)
        self.menuView.addSeparator()
        self.menuTools.addAction(self.actionOptions)
        self.menuTools.addSeparator()
        self.menuTools.addAction(self.actionFast_cmd)
        self.menuTools.addSeparator()
        self.menuShow.addAction(self.actionTime)
        self.menuShow.addSeparator()
        self.menuShow.addAction(self.actionASCII)
        self.menuShow.addAction(self.actionHEX)
        self.menuShow.addSeparator()
        self.menuShow.addAction(self.actionSendASCII)
        self.menuShow.addAction(self.actionSendHEX)
        self.menuShow.addSeparator()
        self.menuOption.addAction(self.menuShow.menuAction())
        self.menuOption.addAction(self.actionhideright)
        self.menuOption.addAction(self.actionhideSend)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuView.menuAction())
        self.menubar.addAction(self.menuTools.menuAction())
        self.menubar.addAction(self.menuOption.menuAction())
        self.menubar.addAction(self.menuWindow.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.toolBar.addAction(self.actionNew)
        self.toolBar.addAction(self.actionOpen)
        self.toolBar.addAction(self.actionRe_Connect)
        self.toolBar.addAction(self.actionDisconnect)
        self.toolBar.addAction(self.menuShow.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.buttonSend.setText(_translate("MainWindow", "发送"))
        self.buttonSend_2.setText(_translate("MainWindow", "自定义发送"))
        self.groupBox_3.setTitle(_translate("MainWindow", "其他设置"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_serial), _translate("MainWindow", "发送设置"))
        self.groupBox.setTitle(_translate("MainWindow", "IPC解析"))
        self.label.setText(_translate("MainWindow", "原始数据"))
        self.label_2.setText(_translate("MainWindow", "解析数据"))
        self.label_5.setText(_translate("MainWindow", "OS_Log文件"))
        self.label_15.setText(_translate("MainWindow", "IPC协议文件"))
        self.button_ipcparse.setText(_translate("MainWindow", "开始解析"))
        self.groupBox_2.setTitle(_translate("MainWindow", "编码解析"))
        self.label_3.setText(_translate("MainWindow", "转换前数据"))
        self.label_4.setText(_translate("MainWindow", "转换后数据"))
        self.button_transspace.setText(_translate("MainWindow", "空格转换"))
        self.button_transtight.setText(_translate("MainWindow", "紧凑转换"))
        self.button_transbuf.setText(_translate("MainWindow", "数组转换"))
        self.button_transHEX.setText(_translate("MainWindow", "字符 -> HXE"))
        self.button_transchar.setText(_translate("MainWindow", "HEX -> 字符"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_parse), _translate("MainWindow", "数据解析"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_plot), _translate("MainWindow", "波形显示"))
        self.groupBox_4.setTitle(_translate("MainWindow", "编译文件转换"))
        self.label_.setText(_translate("MainWindow", "源文件"))
        self.label_6.setText(_translate("MainWindow", "目标文件"))
        self.label_7.setText(_translate("MainWindow", "起始地址（HEX）"))
        self.label_8.setText(_translate("MainWindow", "结束地址（HEX）"))
        self.label_9.setText(_translate("MainWindow", "起始地址（HEX）"))
        self.label_10.setText(_translate("MainWindow", "结束地址（HEX）"))
        self.label_11.setText(_translate("MainWindow", "填充字符（HEX）"))
        self.label_12.setText(_translate("MainWindow", "起始地址（HEX）"))
        self.label_13.setText(_translate("MainWindow", "结束地址（HEX）"))
        self.label_14.setText(_translate("MainWindow", "源文件2"))
        self.buttonstartTrans.setText(_translate("MainWindow", "开始转换"))
        self.comboBoxfiletrans.setItemText(0, _translate("MainWindow", "HEX->BIN"))
        self.comboBoxfiletrans.setItemText(1, _translate("MainWindow", "BIN->HEX"))
        self.comboBoxfiletrans.setItemText(2, _translate("MainWindow", "BIN->TXT"))
        self.comboBoxfiletrans.setItemText(3, _translate("MainWindow", "TXT->BIN"))
        self.label_16.setText(_translate("MainWindow", "功能选择"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_other), _translate("MainWindow", "其他功能"))
        self.menuFile.setTitle(_translate("MainWindow", "文件"))
        self.menuLog.setTitle(_translate("MainWindow", "日志"))
        self.menuEdit.setTitle(_translate("MainWindow", "编辑"))
        self.menuView.setTitle(_translate("MainWindow", "查看"))
        self.menuTools.setTitle(_translate("MainWindow", "工具"))
        self.menuOption.setTitle(_translate("MainWindow", "选项卡"))
        self.menuShow.setTitle(_translate("MainWindow", "显示"))
        self.menuWindow.setTitle(_translate("MainWindow", "窗口"))
        self.menuHelp.setTitle(_translate("MainWindow", "帮助"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.actionOpen.setText(_translate("MainWindow", "打开"))
        self.actionDisconnect.setText(_translate("MainWindow", "断开"))
        self.actionRe_Connect.setText(_translate("MainWindow", "重连"))
        self.actionImport.setText(_translate("MainWindow", "导入"))
        self.actionExport.setText(_translate("MainWindow", "导出"))
        self.actionSave.setText(_translate("MainWindow", "保存"))
        self.actionOtherSave.setText(_translate("MainWindow", "另存为"))
        self.actionStart.setText(_translate("MainWindow", "开始"))
        self.actionStop.setText(_translate("MainWindow", "停止"))
        self.actionPause.setText(_translate("MainWindow", "暂停"))
        self.actionContinue.setText(_translate("MainWindow", "继续"))
        self.actionOpenFile.setText(_translate("MainWindow", "打开文件夹"))
        self.actionOpenLog.setText(_translate("MainWindow", "打开日志"))
        self.actionCopy.setText(_translate("MainWindow", "复制"))
        self.actionPaste.setText(_translate("MainWindow", "粘贴"))
        self.actionCut.setText(_translate("MainWindow", "剪切"))
        self.actionClear.setText(_translate("MainWindow", "清屏"))
        self.actionClearCache.setText(_translate("MainWindow", "清缓存"))
        self.actionClear_All.setText(_translate("MainWindow", "清屏和缓存"))
        self.actionFind.setText(_translate("MainWindow", "查找"))
        self.actionFind_All.setText(_translate("MainWindow", "查找所有"))
        self.actionOptions.setText(_translate("MainWindow", "选项"))
        self.actionFast_cmd.setText(_translate("MainWindow", "快速指令"))
        self.actionTime.setText(_translate("MainWindow", "显示时间"))
        self.actionNew.setText(_translate("MainWindow", "新建"))
        self.actionASCII.setText(_translate("MainWindow", "ASCII"))
        self.actionHEX.setText(_translate("MainWindow", "HEX"))
        self.actionSendASCII.setText(_translate("MainWindow", "发送ASCII"))
        self.actionSendHEX.setText(_translate("MainWindow", "发送HEX"))
        self.actionhideright.setText(_translate("MainWindow", "隐藏右侧"))
        self.actionhideSend.setText(_translate("MainWindow", "隐藏发送栏"))
