# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'newconncet.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_newConnect(object):
    def setupUi(self, newConnect):
        newConnect.setObjectName("newConnect")
        newConnect.resize(351, 381)
        self.verticalLayout = QtWidgets.QVBoxLayout(newConnect)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(10, -1, 10, -1)
        self.horizontalLayout_2.setSpacing(30)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.labelName = QtWidgets.QLabel(newConnect)
        self.labelName.setObjectName("labelName")
        self.horizontalLayout_2.addWidget(self.labelName)
        self.lineEditName = QtWidgets.QLineEdit(newConnect)
        self.lineEditName.setObjectName("lineEditName")
        self.horizontalLayout_2.addWidget(self.lineEditName)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        spacerItem = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout.addItem(spacerItem)
        self.groupBox = QtWidgets.QGroupBox(newConnect)
        self.groupBox.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setContentsMargins(10, 10, 10, 10)
        self.gridLayout.setHorizontalSpacing(60)
        self.gridLayout.setVerticalSpacing(10)
        self.gridLayout.setObjectName("gridLayout")
        self.labelPort = QtWidgets.QLabel(self.groupBox)
        self.labelPort.setObjectName("labelPort")
        self.gridLayout.addWidget(self.labelPort, 0, 0, 1, 1)
        self.comboBoxPort = QtWidgets.QComboBox(self.groupBox)
        self.comboBoxPort.setObjectName("comboBoxPort")
        self.gridLayout.addWidget(self.comboBoxPort, 0, 1, 1, 1)
        self.labelBaud = QtWidgets.QLabel(self.groupBox)
        self.labelBaud.setObjectName("labelBaud")
        self.gridLayout.addWidget(self.labelBaud, 1, 0, 1, 1)
        self.comboBoxBaud = QtWidgets.QComboBox(self.groupBox)
        self.comboBoxBaud.setObjectName("comboBoxBaud")
        self.comboBoxBaud.addItem("")
        self.comboBoxBaud.addItem("")
        self.comboBoxBaud.addItem("")
        self.comboBoxBaud.addItem("")
        self.comboBoxBaud.addItem("")
        self.gridLayout.addWidget(self.comboBoxBaud, 1, 1, 1, 1)
        self.labelData = QtWidgets.QLabel(self.groupBox)
        self.labelData.setObjectName("labelData")
        self.gridLayout.addWidget(self.labelData, 2, 0, 1, 1)
        self.comboBoxData = QtWidgets.QComboBox(self.groupBox)
        self.comboBoxData.setObjectName("comboBoxData")
        self.comboBoxData.addItem("")
        self.comboBoxData.addItem("")
        self.comboBoxData.addItem("")
        self.comboBoxData.addItem("")
        self.gridLayout.addWidget(self.comboBoxData, 2, 1, 1, 1)
        self.labelStop = QtWidgets.QLabel(self.groupBox)
        self.labelStop.setObjectName("labelStop")
        self.gridLayout.addWidget(self.labelStop, 3, 0, 1, 1)
        self.comboBoxStop = QtWidgets.QComboBox(self.groupBox)
        self.comboBoxStop.setObjectName("comboBoxStop")
        self.comboBoxStop.addItem("")
        self.comboBoxStop.addItem("")
        self.comboBoxStop.addItem("")
        self.gridLayout.addWidget(self.comboBoxStop, 3, 1, 1, 1)
        self.labelCheck = QtWidgets.QLabel(self.groupBox)
        self.labelCheck.setObjectName("labelCheck")
        self.gridLayout.addWidget(self.labelCheck, 4, 0, 1, 1)
        self.comboBoxCheck = QtWidgets.QComboBox(self.groupBox)
        self.comboBoxCheck.setObjectName("comboBoxCheck")
        self.comboBoxCheck.addItem("")
        self.comboBoxCheck.addItem("")
        self.comboBoxCheck.addItem("")
        self.comboBoxCheck.addItem("")
        self.gridLayout.addWidget(self.comboBoxCheck, 4, 1, 1, 1)
        self.gridLayout.setColumnMinimumWidth(0, 50)
        self.gridLayout.setColumnMinimumWidth(1, 200)
        self.verticalLayout.addWidget(self.groupBox)
        spacerItem1 = QtWidgets.QSpacerItem(20, 92, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButtonConnect = QtWidgets.QPushButton(newConnect)
        self.pushButtonConnect.setObjectName("pushButtonConnect")
        self.horizontalLayout.addWidget(self.pushButtonConnect)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.pushButtonOK = QtWidgets.QPushButton(newConnect)
        self.pushButtonOK.setObjectName("pushButtonOK")
        self.horizontalLayout.addWidget(self.pushButtonOK)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.pushButtonCancel = QtWidgets.QPushButton(newConnect)
        self.pushButtonCancel.setObjectName("pushButtonCancel")
        self.horizontalLayout.addWidget(self.pushButtonCancel)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.groupBox.raise_()

        self.retranslateUi(newConnect)
        QtCore.QMetaObject.connectSlotsByName(newConnect)

    def retranslateUi(self, newConnect):
        _translate = QtCore.QCoreApplication.translate
        newConnect.setWindowTitle(_translate("newConnect", "新建连接"))
        self.labelName.setText(_translate("newConnect", "名称 ："))
        self.groupBox.setTitle(_translate("newConnect", "串口设置"))
        self.labelPort.setText(_translate("newConnect", "端口  ："))
        self.labelBaud.setText(_translate("newConnect", "波特率："))
        self.comboBoxBaud.setItemText(0, _translate("newConnect", "9600"))
        self.comboBoxBaud.setItemText(1, _translate("newConnect", "14400"))
        self.comboBoxBaud.setItemText(2, _translate("newConnect", "19200"))
        self.comboBoxBaud.setItemText(3, _translate("newConnect", "38400"))
        self.comboBoxBaud.setItemText(4, _translate("newConnect", "115200"))
        self.labelData.setText(_translate("newConnect", "数据位："))
        self.comboBoxData.setCurrentText(_translate("newConnect", "8"))
        self.comboBoxData.setItemText(0, _translate("newConnect", "8"))
        self.comboBoxData.setItemText(1, _translate("newConnect", "7"))
        self.comboBoxData.setItemText(2, _translate("newConnect", "6"))
        self.comboBoxData.setItemText(3, _translate("newConnect", "5"))
        self.labelStop.setText(_translate("newConnect", "停止位："))
        self.comboBoxStop.setItemText(0, _translate("newConnect", "1"))
        self.comboBoxStop.setItemText(1, _translate("newConnect", "1.5"))
        self.comboBoxStop.setItemText(2, _translate("newConnect", "2"))
        self.labelCheck.setText(_translate("newConnect", "校验位："))
        self.comboBoxCheck.setItemText(0, _translate("newConnect", "None"))
        self.comboBoxCheck.setItemText(1, _translate("newConnect", "Odd"))
        self.comboBoxCheck.setItemText(2, _translate("newConnect", "Even"))
        self.comboBoxCheck.setItemText(3, _translate("newConnect", "Mark"))
        self.pushButtonConnect.setText(_translate("newConnect", "连接"))
        self.pushButtonOK.setText(_translate("newConnect", "确定"))
        self.pushButtonCancel.setText(_translate("newConnect", "取消"))
